config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  [:sports, :sport_complexes, :sport_organizations, :clubs, :competitions].each do |action|
    resources action, only: %i[index new create]
  end

  [:participants, :requests, :results].each do |action|
    resources action, only: %i[index new create edit update]
  end

  get 'participants_list_download' => 'participants#download_list', format: 'docx'
  get 'requests_list_download' => 'requests#download_list', format: 'docx'
  get 'results_report_download' => 'results#download_list', format: 'docx'
  root 'sports#index'
end

app/models/sport.rb
class Sport < ApplicationRecord
  has_many :clubs
  has_many :competitions

  validates_presence_of :name
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController

  def new
    @sport = Sport.new
  end

  def create
    @sport = Sport.new(sport_params)
    if @sport.save
      redirect_to sports_path
    else
      render 'new'
    end
  end

  def index
    @q = Sport.ransack(params[:q])
    @sports = @q.result
  end

  private

  def sport_params
    params.require(:sport).permit(:name, :organizator, :date, :sport_id, :sport_complex_id)
  end
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/views/sports/index.html.slim
h1 Виды спорта
= search_form_for @q  do |f|
  .row.mt-3
    .col
      = link_to 'Новый', new_sport_path, class: "btn btn-outline-primary"
    .col-md-3.align-self-end
      .input-group.mb-2
        .input-group-prepend
          .input-group-text Найти
        = f.search_field :name_cont, class: 'form-control'
.row.mt-3
  .col-md
    table.table
      thead
        tr
          th #
          th Название
      tbody
        - @sports.each do |sport|
          tr
            td = sport.id
            td
              = link_to sport.name, competitions_path(q: {sport_id_eq: sport})

app/views/sports/new.html.slim
h1 Новый вид спорта
= form_for @sport, url: { action: :create }, html: { class: 'mt-3 form-row' } do |f|
  .form-group.col-md-6
    = f.label 'Название*'
    = f.text_field :name, class: 'form-control'
  .form-group.col-md-7
    p.text-muted * - Обязательное поле
  .form-group.col-md-7
    = f.submit 'Создать', class: 'btn btn-primary'