config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  [:sports, :sport_complexes, :sport_organizations, :clubs, :competitions].each do |action|
    resources action, only: %i[index new create]
  end

  [:participants, :requests, :results].each do |action|
    resources action, only: %i[index new create edit update]
  end

  get 'participants_list_download' => 'participants#download_list', format: 'docx'
  get 'requests_list_download' => 'requests#download_list', format: 'docx'
  get 'results_report_download' => 'results#download_list', format: 'docx'
  root 'sports#index'
end

app/models/competition.rb
class Competition < ApplicationRecord
  belongs_to :sport
  belongs_to :sport_complex
  has_many :requests, dependent: :destroy
  has_many :participants, through: :requests

  validates_presence_of :name
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :club, optional: true
  has_many :requests, dependent: :destroy
  has_many :competitions, through: :requests

  validates_presence_of :name, :age, :growth, :weight
  validates :age, inclusion: 5..90
  validates :growth, inclusion: 90..400
  validates :weight, inclusion: 20..300
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :find_participant, only: %i[edit update]
  respond_to :docx

  def new
    @participant = Participant.new
  end

  def create
    @participant = Participant.new(participant_params)
    if @participant.save
      redirect_to participants_path
    else
      render 'new'
    end
  end

  def index
    @q = Participant.ransack(params[:q])
    @participants = @q.result
  end

  def edit;end

  def update
    if @participant.update(participant_params)
      redirect_to participants_path
    else
      render 'edit'
    end
  end

  def download_list
    @participants = Participant.find(params[:participant_ids])
    respond_to do |format|
      format.docx { render docx: 'participants_list', filename: 'participants_list.docx' }
    end
  end

  private

  def find_participant
    @participant = Participant.find(params[:id])
  end

  def participant_params
    params.require(:participant).permit(:name, :age, :growth, :weight, :club_id)
  end
end

app/views/participants/_form.html.slim
= form_for @participant, html: { class: 'mt-3 form-row' } do |f|
  .form-group.col-md-7
    = f.label 'ФИО*'
    = f.text_field :name, class: 'form-control'
  .form-group.col-md-7
    = f.label 'Возраст*'
    = f.text_field :age, class: 'form-control'
  .form-group.col-md-7
    = f.label 'Рост*'
    = f.text_field :growth, class: 'form-control'
  .form-group.col-md-7
    = f.label 'Вес*'
    = f.text_field :weight, class: 'form-control'
  .form-group.col-md-7
    = f.label 'Клуб'
    = f.select :club_id, Club.all.decorate.collect {|u| [u.short_info, u.id]}, { prompt: 'Не указано' }, { class: 'form-control' }
  .form-group.col-md-7
    p.text-muted * - Обязательное поле
  .form-group.col-md-7
    = f.submit 'Применить', class: 'btn btn-primary'

app/views/participants/_table_form.html.slim
table.table
  thead
    tr
      th #
      th ФИО участника
      th Возраст
      th Рост
      th Вес
      th Клуб
      - if local_assigns[:update_link]
        th
          i.fa.fa-pencil-square-o
  tbody
    - @participants.each do |participant|
      tr
        td = participant.id
        td
          = link_to participant.name, requests_path(q: {participant_id_eq: participant})
        td = participant.age
        td = participant.growth
        td = participant.weight
        td = participant.decorate.club_name
        - if local_assigns[:update_link]
          td
            = link_to edit_participant_path(participant)
              i.fa.fa-pencil-square-o

app/views/participants/edit.html.slim
h1 Редактирование участника
= render 'form'

app/views/participants/index.html.slim
h1 Участники
= search_form_for @q do |f|
  .row.mt-3
    .col
      .btn-group role="group"
        = link_to 'Новый', new_participant_path, class: "btn btn-outline-primary"
        = link_to participants_list_download_path(participant_ids: @participants.to_a), class: 'btn btn-primary', 'data-toggle' => 'tooltip',
         'title' => 'Скачать список docx' do
          i.fa.fa-download
        button.btn.btn-primary type="button" data-toggle="collapse" data-target="#filterCollapse" aria-expanded="false" aria-controls="filterCollapse"
          i.fa.fa-filter
    .col-md-3.align-self-end
      .input-group.mb-2
        .input-group-prepend
          .input-group-text Найти
        = f.search_field :name_cont, class: 'form-control'
  .row.mt-3.collapse id = "filterCollapse"
    .col-md-4
      = f.label 'По клубу'
      = f.select :club_id_in, Club.all.decorate.collect {|u| [u.short_info, u.id]}, { include_blank: 'Не указано' }, { multiple: true }
      .btn-group.mt-3 role="group"
        = f.submit 'Фильтровать', class: 'btn btn-primary'
        = link_to participants_path, class: 'btn btn-outline-primary'
          i.fa.fa-times
.row.mt-3
  .col-md
    = render 'table_form', update_link: true

app/views/participants/new.html.slim
h1 Новый участник
= render 'form'

app/views/participants/participants_list.docx.slim
= render partial: 'table_form', formats: [:html], update_link: false