config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  [:sports, :sport_complexes, :sport_organizations, :clubs, :competitions].each do |action|
    resources action, only: %i[index new create]
  end

  [:participants, :requests, :results].each do |action|
    resources action, only: %i[index new create edit update]
  end

  get 'participants_list_download' => 'participants#download_list', format: 'docx'
  get 'requests_list_download' => 'requests#download_list', format: 'docx'
  get 'results_report_download' => 'results#download_list', format: 'docx'
  root 'sports#index'
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :request

  validates_presence_of :place
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :find_result, only: [:edit, :update]
  respond_to :docx

  def new
    @result = Result.new
  end

  def create
    @result = Result.new(result_params)
    if @result.save
      redirect_to results_path
    else
      render 'new'
    end
  end

  def index
    @q = Result.ransack(params[:q])
    @results = @q.result
  end

  def edit; end

  def update
    if @result.update(result_params.except(:request_id))
      redirect_to results_path
    else
      render 'edit'
    end
  end

  def download_list
    @results = Result.find(params[:result_ids])
    respond_to do |format|
      format.docx { render docx: 'results_report', filename: 'results_report.docx' }
    end
  end

  private
  def find_result
    @result = Result.find(params[:id])
  end

  def result_params
    params.require(:result).permit(:place, :height_result, :length_result, :score, :request_id)
  end
end

app/helpers/results_helper.rb
module ResultsHelper
  def form_params
    params[:action] == 'new' ? {header: 'Создание результата', create_form: true, submit: 'Создать'}\
    : {header: 'Редактирование результата', submit: 'Обновить'}
  end
end

app/views/results/_form.html.slim
h1 = local_assigns[:header] || ''
= form_for @result, html: { class: 'mt-3 form-row' } do |f|
  - if local_assigns[:create_form]
    .form-group.col-md-7
      = f.label 'Заявка*'
      = f.select :request_id, Request.all.decorate.collect {|u| [u.display_name, u.id] }, {}, { class: 'form-control' }
  .form-group.col-md-7
    = f.label 'Место*'
    = f.text_field :place, class: 'form-control'
  .form-group.col-md-7
    = f.label 'Счет'
    = f.text_field :score, class: 'form-control'
  .form-group.col-md-7
    = f.label 'Длина'
    = f.text_field :length_result, class: 'form-control'
  .form-group.col-md-7
    = f.label 'Высота'
    = f.text_field :height_result, class: 'form-control'
  .form-group.col-md-7
    p.text-muted * - Обязательное поле
  .form-group.col-md-7
    = f.submit local_assigns[:submit], class: 'btn btn-primary'

app/views/results/_table_form.html.slim
table.table
  thead
    tr
      th #
      th Участник
      th Соревнование
      th Место
      th Длина
      th Высота
      th Счет
      - if local_assigns[:update_link]
        th
          i.fa.fa-pencil-square-o
  tbody
    - @results.each do |result|
      tr
        td = result.id
        td = result.request.decorate.short_display_name
        td = result.request.competition.name
        td = result.place
        td = result.length_result.presence || 'Не указано'
        td = result.height_result.presence || 'Не указано'
        td = result.score.presence || 'Не указано'
        td
          = link_to edit_result_path(result)
            i.fa.fa-pencil-square-o

app/views/results/edit.html.slim
= render 'form', form_params

app/views/results/index.html.slim
h1 Результаты
= search_form_for @q do |f|
  .row.mt-3
    .col
      .btn-group role="group"
        = link_to 'Новый', new_result_path, class: "btn btn-outline-primary"
        = link_to results_report_download_path(result_ids: @results.to_a), class: 'btn btn-primary', 'data-toggle' => 'tooltip',
           'title' => 'Скачать список docx' do
           i.fa.fa-download
        button.btn.btn-primary type="button" data-toggle="collapse" data-target="#filterCollapse" aria-expanded="false" aria-controls="filterCollapse"
          i.fa.fa-filter
  .row.collapse.mt-3 id="filterCollapse"
    .col-md-4
      .form-group
        = f.label 'По соревнованию'
        = f.select :request_competition_id_eq, Competition.all.collect {|u| [u.name, u.id]}, {prompt: 'Не указано'}
      .btn-group role="group"
        = f.submit 'Фильтровать', class: 'btn btn-primary'
        = link_to results_path, class: 'btn btn-outline-primary'
          i.fa.fa-times
.row.mt-3
  .col-md
    = render 'table_form', update_link: true

app/views/results/new.html.slim
h1.mt-3 Новый результат
= form_for @result, url: { action: :create }, html: { class: 'mt-3 form-row' } do |f|
  .form-group.col-md-7
    = f.label 'Заявка*'
    = f.select :request_id, Request.all.decorate.collect {|u| [u.result_title, u.id] }, {}, { class: 'form-control' }
  .form-group.col-md-7
    = f.label 'Место*'
    = f.text_field :place, class: 'form-control'
  .form-group.col-md-7
    = f.label 'Счет'
    = f.text_field :score, class: 'form-control'
  .form-group.col-md-7
    = f.label 'Длина'
    = f.text_field :length_result, class: 'form-control'
  .form-group.col-md-7
    = f.label 'Высота'
    = f.text_field :height_result, class: 'form-control'
  .form-group.col-md-7
    p.text-muted * - Обязательное поле
  .form-group.col-md-7
    = f.submit 'Создать', class: 'btn btn-primary'

app/views/results/results_report.docx.slim
= render partial: 'table_form', formats: [:html]