config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  [:sports, :sport_complexes, :sport_organizations, :clubs, :competitions].each do |action|
    resources action, only: %i[index new create]
  end

  [:participants, :requests, :results].each do |action|
    resources action, only: %i[index new create edit update]
  end

  get 'participants_list_download' => 'participants#download_list', format: 'docx'
  get 'requests_list_download' => 'requests#download_list', format: 'docx'
  get 'results_report_download' => 'results#download_list', format: 'docx'
  root 'sports#index'
end

app/models/club.rb
class Club < ApplicationRecord
  belongs_to :sport_organization
  belongs_to :sport
  has_many :requests

  validates_presence_of :name

  enum club_type: { "Детский" => 0 , "Юношеский" => 1 , "Взрослый" => 2 }
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :participant, optional: true
  belongs_to :club, optional: true
  belongs_to :competition
  has_one :result, dependent: :destroy

  before_save :nullify_is_ill_for_clubs
  validate :validate_participant_or_club
  validates_uniqueness_of :participant_id, scope: [:competition_id], unless: :club_id?
  validates_uniqueness_of :club_id, scope: [:competition_id], unless: :participant_id?

  def validate_participant_or_club
    if !participant_id && !club_id
      errors.add("#{:participant_id} и #{:club_id}", 'не могут быть оба пустыми')
    end
    if participant_id && club_id
      errors.add('', 'Вы должны выбрать только одно')
    end
  end

  def nullify_is_ill_for_clubs
    self.is_ill = nil if club_id
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :find_request, only: %i[edit update]
  respond_to :docx

  def new
    @request = Request.new
  end

  def create
    @request = Request.new(request_params)
    if @request.save
      redirect_to requests_path
    else
      render 'new'
    end
  end

  def index
    @q = Request.ransack(params[:q])
    @requests = @q.result
  end

  def edit;end

  def update
    if @request.update(request_params)
      redirect_to requests_path
    else
      render 'edit'
    end
  end

  def download_list
    @requests = Request.find(params[:request_ids])
    respond_to do |format|
      format.docx { render docx: 'requests_list', filename: 'requests_list.docx' }
    end
  end

  private

  def find_request
    @request = Request.find(params[:id])
  end

  def request_params
    params.require(:request).permit(:is_ill, :appeared, :participant_id, :competition_id, :club_id)
  end
end

app/helpers/requests_helper.rb
module RequestsHelper
  def yesno(boolean)
    return 'Да' if boolean == true
    return 'Нет' if boolean == false
    'Не указано'
  end
end

app/views/requests/_form.html.slim
= form_for @request, html: { class: 'mt-3 form-row' } do |f|
  - if controller_name == "requests" && action_name == "edit" && @request.participant || action_name == "new" || action_name == "create"
    #requestParticipantSelector.form-group.col-md-7
      = f.label 'Участник'
      = f.select :participant_id, Participant.all.decorate.collect {|u| [u.short_info, u.id]}, {prompt: 'Не указано' }, { class: 'form-control' }
  - if controller_name == "requests" && action_name == "edit" && @request.club || action_name == "new" || action_name == "create"
    #requestClubSelector.form-group.col-md-7
      = f.label 'Спортивный клуб'
      = f.select :club_id, Club.all.decorate.collect {|u| [u.short_info, u.id]}, {prompt: 'Не указано' }, { class: 'form-control' }
  .form-group.col-md-7
    = f.label 'Соревнование*'
    = f.select :competition_id, Competition.all.collect {|u| [u.name, u.id]}, {}, { class: 'form-control' }
  - if controller_name == "requests" && action_name == "edit" && @request.is_ill || action_name == "new" || action_name == "create"
    #requestIsIllSelector.form-group.col-md-7
      = f.label 'Болен*'
      = f.select :is_ill, [['Да', true], ['Нет', false]], {}, { class: 'form-control' }
  .form-group.col-md-7
    = f.label 'Явился*'
    = f.select :appeared, [['Да', true], ['Нет', false]], {}, { class: 'form-control' }
  .form-group.col-md-7
    p.text-muted * - Обязательное поле
  .form-group.col-md-7
    = f.submit 'Применить', class: 'btn btn-primary'

app/views/requests/_table_form.html.slim
table.table
  thead
    tr
      th #
      th Заявка
      th Болен
      th Явился
      - if local_assigns[:update_link]
        th
          i.fa.fa-pencil-square-o
  tbody
    - @requests.each do |request|
      tr
        td = request.id
        td
          = link_to request.decorate.display_name, results_path(q: {request_id_eq: request})
        td = yesno(request.is_ill)
        td = yesno(request.appeared)
        - if local_assigns[:update_link]
          td
            = link_to edit_request_path(request)
              i.fa.fa-pencil-square-o

app/views/requests/edit.html.slim
h1 Редактировать заявку
= render 'form'

app/views/requests/index.html.slim
h1 Заявки
= search_form_for @q do |f|
  .row.mt-3
    .col
      .btn-group role="group"
        = link_to 'Новый', new_request_path, class: "btn btn-outline-primary"
        = link_to requests_list_download_path(request_ids: @requests.to_a), class: 'btn btn-primary', 'data-toggle' => 'tooltip',
           'title' => 'Скачать список docx' do
           i.fa.fa-download
        button.btn.btn-primary type="button" data-toggle="collapse" data-target="#filterCollapse" aria-expanded="false" aria-controls="filterCollapse"
          i.fa.fa-filter
  .row.collapse.mt-3 id="filterCollapse"
    .col-md-4
      .form-group
        = f.label 'По соревнованию'
        = f.select :competition_id_eq, Competition.all.collect {|u| [u.name, u.id]}, {prompt: 'Не указано'}
      .form-group
        = f.label 'Болен'
        = f.select :is_ill_eq, [['Да', true], ['Нет', false]], {prompt: 'Не указано'}
      .form-group
        = f.label 'Явился'
        = f.select :appeared_eq, [['Да', true], ['Нет', false]], {prompt: 'Не указано'}
      .btn-group role="group"
        = f.submit 'Фильтровать', class: 'btn btn-primary'
        = link_to requests_path, class: 'btn btn-outline-primary'
          i.fa.fa-times
.row.mt-3
  .col-md
    = render 'table_form', update_link: true

app/views/requests/new.html.slim
h1.d-inline Новая заявка
a href="#" onclick="$('#dialogOnRequest').modal('show')"
  i.fa.fa-cog.d-inline.ml-3
= render 'form'
#dialogOnRequest.modal.fade aria-hidden="true" role="dialog" tabindex="-1" data-backdrop="static"
  .modal-dialog
    .modal-content
      .modal-header
        h2 Выберите действие
      .modal-body
        p Вы собираетесь создать заявку на командное соревнование?
      .modal-footer
        button.btn.btn-primary onclick="clubRequest()" Да
        button.btn.btn-primary onclick="participantRequest()" Нет

app/views/requests/requests_list.docx.slim
= render partial: 'table_form', formats: [:html], update_link: false